const predefinedTags = [
  { id: "1", name: "Acoustic" },
  { id: "2", name: "Electronic" },
  { id: "3", name: "Distorted" },
  { id: "4", name: "Clean" },
  { id: "5", name: "Bright" },
  { id: "6", name: "Dark" },
  { id: "7", name: "Warm" },
  { id: "8", name: "Cold" },
  { id: "9", name: "Metallic" },
  { id: "10", name: "Wooden" },
  { id: "11", name: "Slow" },
  { id: "12", name: "Medium" },
  { id: "13", name: "Fast" },
  { id: "14", name: "Upbeat" },
  { id: "15", name: "Downbeat" },
  { id: "16", name: "Rhythmic" },
  { id: "17", name: "Syncopated" },
  { id: "18", name: "Steady" },
  { id: "19", name: "Variable" },
  { id: "20", name: "Loop" },
  { id: "21", name: "Energetic" },
  { id: "22", name: "Relaxed" },
  { id: "23", name: "Melancholic" },
  { id: "24", name: "Happy" },
  { id: "25", name: "Sad" },
  { id: "26", name: "Aggressive" },
  { id: "27", name: "Soothing" },
  { id: "28", name: "Mysterious" },
  { id: "29", name: "Romantic" },
  { id: "30", name: "Uplifting" },
  { id: "31", name: "Cinematic" },
  { id: "32", name: "Vintage" },
  { id: "33", name: "Modern" },
  { id: "34", name: "Futuristic" },
  { id: "35", name: "Ethnic" },
  { id: "36", name: "Experimental" },
  { id: "37", name: "Ambient" },
  { id: "38", name: "Textured" },
  { id: "39", name: "Spatial" },
  { id: "40", name: "Layered" },
];

export default predefinedTags;
